version: '3.3'

services:
    back:
        # image: "ghcr.io/procharity/procharity_bot_back_prod"
        image: "anzeky/procharity_bot_back_prod"
        restart: "always"
        depends_on:
            - db
        expose:
            - "8000"
            - "5000"
        ports:
            -   "8000:8000"
        env_file:
            -   .env
        volumes:
            - /code/logs:/back/logs
            - /code/data:/back/bot_persistence_file/

    front:
        # image: "ghcr.io/procharity/procharity_bot_front_prod"
        image: "anzeky/procharity_bot_front_prod"
        restart: "always"
        depends_on:
            - back
        env_file:
            -   .env
        ports:
            - "80:80"
            - "443:443"
        volumes:
            -   /etc/nginx/ssl:/etc/nginx/ssl
            -   /code/nginx_logs:/var/log/nginx
    db:
        image: postgres:12-alpine
        restart: "always"
        volumes:
            -   postgres_data:/var/lib/postgresql/data
        expose:
            - "5432"
        ports:
            - "9999:5432"
        env_file:
            -   .env

volumes:
    postgres_data:
