version: '3.3'

services:
    back:
        image: "ghcr.io/procharity/procharity_bot_back"
        expose:
            - "8000"
            - "5000"
        ports:
            -   "8000:8000"
        env_file:
            -   .env
        volumes:
            - /code/logs:/back/logs
            - /code/data:/back/bot_persistence_file/
            - /etc/nginx/ssl:/back/ssl_cert

    front:
        image: "ghcr.io/procharity/procharity_bot_front_prod"
        env_file:
            -   .env
        ports:
            - "80:80"
            - "443:443"
    db:
        image: postgres:12-alpine
        volumes:
            -   postgres_data:/var/lib/postgresql/data
        expose:
            - "5432"
        ports:
            - "9999:5432"
        env_file:
            -   .env

volumes:
    postgres_data:
