version: '3.3'

services:
    back:
        build:
            context: .
            dockerfile: .

        restart: always
        network_mode: "host"

    front:
        build:
            context: ./front
            dockerfile: Dockerfile
        expose:
            -   "80"
