version: '3.3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=procharity
      - POSTGRES_PASSWORD=procharity
      - POSTGRES_DB=procharity_local_test_db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data: