version: '3.3'

services:
    back:
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: "host"
        restart: always
#        expose:
#            - "8000:8000"

    nginx_front:
        build:
            context: front
            dockerfile: Dockerfile
        expose:
            - "80"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            -   back