version: '3.8'

services:
    back:
        build: .
        expose:
            - "8000"
            - "5000"
        env_file:
            -   .env.dev

    front:
        build: front/
        ports:
            -    "80:80"
    db:
        image: postgres:12-alpine
        volumes:
            -   postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=procharity
            - POSTGRES_PASSWORD=procharity
            - POSTGRES_DB=procharity_local_test_db
        expose:
            - "5432"
        ports:
            - "9999:5432"

volumes:
    postgres_data:
