
###

POST http://localhost:5000/api/webhook/categories/
Content-Type: application/json


{
   "categories": [
  {
      "id":"111",
      "name":"Дизайн и верстка"
   },
   {
       "id":"2",
      "name":"Маркетинг и коммуникации"

   },
   {
       "id":"333",
      "name":"Всего понемногу"
   },
   {
       "id":"4",
      "name":"Всякая всячина"
   },
   {
       "id":"5",
      "name":"IT"
   },
   {
       "id":"6",
      "name":"Переводы"
   },
   {
       "id":"7",
      "name":"Менеджмент"
   },
   {
       "id":"12",
      "name":"Фото и видео"
   }
    ]
}


###

POST http://localhost:5000/api/webhook/tasks/
Content-Type: application/json

{
    "tasks": [
        {
      "id":"11123456",
      "title":"Создание семантического ядра111",
      "name_organization":"фонд СеллСтандарт",
      "deadline":"25.06.2021",
      "category":"Маркетинг и коммуникации",
      "category_id":"2",
      "bonus":"4",
      "location":"Санкт-Петербург",
      "link":"<https://procharity.ru/tasks/detail.php?ID=32539>",
      "description":""
   }, 
   {
      "id":"2222345",
      "title":"Видеосъемка фильма о проекте22",
      "name_organization":"БФ «Гольфстрим»",
      "deadline":"21.06.2021",
      "category":"Фото и видео",
      "category_id":"12",
      "bonus":"5",
      "location":"Москва",
      "link":"<https://procharity.ru/tasks/detail.php?ID=33098>",
      "description":""
   }
    ]

   
}

