COMMAND__ABOUT = 'about'
COMMAND__OPEN_MENU = 'open_menu'
COMMAND__OPEN_TASK = 'open_task'
COMMAND__CHANGE_CATEGORY = 'change_category'
COMMAND__RETURN_CHOSE_CATEGORY = 'return_chose_category'
COMMAND__READY = 'ready'
COMMAND__NO_RELEVANT = 'no_relevant'
COMMAND__ASK_QUESTION = 'ask_question'
COMMAND__NEW_FEATURE = 'new_feature'
COMMAND__ASK_NEW_CATEGORY = 'ask_new_category'
COMMAND__NO_WAIT = 'no_wait'
COMMAND__START_SUBSCRIPTION ='start_subscription'
COMMAND__STOP_SUBSCRIPTION = 'stop_subscription'
COMMAND__GREETING = 'choose_category_after_start'
COMMAND__GREETING_REGISTERED_USER = 'before_confirm_specializations'


CANCEL_FEEDBACK__MANY_NOTIFICATION = 'many_notification'
CANCEL_FEEDBACK__NO_TIME = 'no_time'
CANCEL_FEEDBACK__NO_RELEVANT_TASK = 'no_relevant_task'
CANCEL_FEEDBACK__BOT_IS_BAD = 'bot_is_bad'
CANCEL_FEEDBACK__FOND_IGNORE = 'fond_ignore'
CANCEL_FEEDBACK__ANOTHER = 'another'
