"""message

Revision ID: 129f7a1accfd
Revises: 64297b9f91eb
Create Date: 2021-06-22 06:30:06.000757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129f7a1accfd'
down_revision = '64297b9f91eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(length=9), nullable=True),
    sa.Column('command', sa.String(length=100), nullable=True),
    sa.Column('added_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('category', 'category_api_id')
    op.drop_column('task', 'task_api_id')
    op.alter_column('user', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('task', sa.Column('task_api_id', sa.INTEGER(), nullable=True))
    op.add_column('category', sa.Column('category_api_id', sa.INTEGER(), nullable=True))
    op.drop_table('statistics')
    # ### end Alembic commands ###
