"""message

Revision ID: 316ec7b5f182
Revises: 64297b9f91eb
Create Date: 2021-06-21 22:27:23.414345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316ec7b5f182'
down_revision = '64297b9f91eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('command', sa.String(length=100), nullable=True),
    sa.Column('added_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('category', 'category_api_id')
    op.drop_column('task', 'task_api_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_api_id', sa.INTEGER(), nullable=True))
    op.add_column('category', sa.Column('category_api_id', sa.INTEGER(), nullable=True))
    op.drop_table('statistics')
    # ### end Alembic commands ###
