"""Change subcategories column in Category

Revision ID: 35477a4b423e
Revises: 52647dd43d55
Create Date: 2022-09-21 20:46:12.439723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35477a4b423e'
down_revision = '52647dd43d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
