"""add external_signup_date column to User

Revision ID: 3934b69146c0
Revises: 7e3358b5b907
Create Date: 2021-08-05 00:29:18.630027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3934b69146c0'
down_revision = '7e3358b5b907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_signup_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'external_signup_date')
    # ### end Alembic commands ###
