"""added fields created_date, update_date in tasks

Revision ID: 39982a380a7b
Revises: 8accfa4587dd
Create Date: 2021-07-07 18:31:21.285135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39982a380a7b'
down_revision = '8accfa4587dd'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    if bind.engine.name == 'sqlite':
        op.add_column('tasks', sa.Column('created_date', sa.DateTime(), server_default=sa.text('(DATETIME())'), nullable=False))
        op.add_column('tasks', sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(DATETIME())'), nullable=False))
    else:   
        op.add_column('tasks', sa.Column('created_date', sa.DateTime(), server_default=sa.text('(now())'), nullable=False))
        op.add_column('tasks', sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(now())'), nullable=False))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_date')
    op.drop_column('tasks', 'created_date')
    # ### end Alembic commands ###
