"""test

Revision ID: 39c007beee2e
Revises: 3ac146ccf4f5
Create Date: 2021-09-30 13:43:42.571097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39c007beee2e'
down_revision = '3ac146ccf4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistics', 'added_date', existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
    op.alter_column('admin_users', 'last_logon', existing_type=sa.DateTime(),
                    type_=sa.TIMESTAMP(), nullable=True)
    op.alter_column('users', 'external_signup_date', existing_type=sa.DateTime(),
                    type_=sa.TIMESTAMP(), nullable=True)
    op.alter_column('notifications', 'sent_date', existing_type=sa.DateTime(),
                    type_=sa.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistics', 'added_date', existing_type=sa.TIMESTAMP(),
                    type_=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column('admin_users', 'last_logon', existing_type=sa.TIMESTAMP(),
                    type_=sa.DateTime(), nullable=True)
    op.alter_column('users', 'external_signup_date', existing_type=sa.TIMESTAMP(),
                    type_=sa.DateTime(), nullable=True)
    op.alter_column('notifications', 'sent_date', existing_type=sa.TIMESTAMP(),
                    type_=sa.DateTime(), nullable=True)
    # ### end Alembic commands ###
