"""alter_datetime_columns

Revision ID: 3ac146ccf4f5
Revises: 207f6c755575
Create Date: 2021-09-29 16:13:08.601271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ac146ccf4f5'
down_revision = '207f6c755575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_site_users', 'created_date', existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
    op.alter_column('external_site_users', 'updated_date', existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
    op.alter_column('tasks', 'created_date', existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
    op.alter_column('tasks', 'updated_date', existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
    op.alter_column('users', 'date_registration', existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_site_users', 'created_date', existing_type=sa.TIMESTAMP(),
                    type_=postgresql.TIMESTAMP(), nullable=False, server_default=sa.text('now()'))  
    op.alter_column('external_site_users', 'updated_date', existing_type=sa.TIMESTAMP(),
                    type_=postgresql.TIMESTAMP(), nullable=False, server_default=sa.text('now()'))     
    op.alter_column('tasks', 'created_date', existing_type=sa.TIMESTAMP(),
                    type_=postgresql.TIMESTAMP(), nullable=False, server_default=sa.text('now()'))   
    op.alter_column('tasks', 'updated_date', existing_type=sa.TIMESTAMP(),
                    type_=postgresql.TIMESTAMP(), nullable=False, server_default=sa.text('now()'))     
    op.alter_column('users', 'date_registration', existing_type=sa.TIMESTAMP(),
                    type_=postgresql.TIMESTAMP(), nullable=False)
    # ### end Alembic commands ###
