"""message

Revision ID: 518696c0a81c
Revises: e327138d56b1
Create Date: 2021-06-19 23:38:40.398105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518696c0a81c'
down_revision = 'e327138d56b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
