"""add_task_history_table

Revision ID: 65df3091067e
Revises: 0ea530c95a28
Create Date: 2021-08-25 19:10:18.090908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65df3091067e'
down_revision = '0ea530c95a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('new_tasks', sa.Integer(), nullable=False),
    sa.Column('updated_tasks', sa.Integer(), nullable=False),
    sa.Column('archived_tasks', sa.Integer(), nullable=False),
    sa.Column('unarchived_tasks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_history')
    # ### end Alembic commands ###
