"""created ExternalSiteUser

Revision ID: 6768bc313cd1
Revises: 39982a380a7b
Create Date: 2021-07-09 23:13:01.051775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6768bc313cd1'
down_revision = '39982a380a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_site_users',
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('external_id_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=48), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('specializations', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('external_id')
    )
    op.alter_column('reasons_canceling', 'added_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'date_registration',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_registration',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reasons_canceling', 'added_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('external_site_users')
    # ### end Alembic commands ###
