"""rename_table_registers

Revision ID: 7e3358b5b907
Revises: 6768bc313cd1
Create Date: 2021-07-28 17:11:37.123739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e3358b5b907'
down_revision = '6768bc313cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('registers', 'admin_registration_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('admin_registration_requests', 'registers')
    # ### end Alembic commands ###
