"""created reasons_canceling

Revision ID: 8accfa4587dd
Revises: ba543de75703
Create Date: 2021-07-06 12:59:36.190218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8accfa4587dd'
down_revision = 'ba543de75703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reasons_canceling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('reason_canceling', sa.String(length=48), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reasons_canceling')
    # ### end Alembic commands ###
