"""added externalsiteuser

Revision ID: 8e33568abb2b
Revises: 39982a380a7b
Create Date: 2021-07-09 22:04:08.593671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e33568abb2b'
down_revision = '39982a380a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_site_users',
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('external_id_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=48), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('specializations', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('external_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_site_users')
    # ### end Alembic commands ###
