"""add_banned_column_to_user_model

Revision ID: 907e59bc7953
Revises: 3934b69146c0
Create Date: 2021-08-11 13:46:02.733014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '907e59bc7953'
down_revision = '3934b69146c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    # ### end Alembic commands ###
