"""added SiteUsers

Revision ID: 93011616ac40
Revises: 8accfa4587dd
Create Date: 2021-07-08 22:43:18.186272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93011616ac40'
down_revision = '8accfa4587dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=48), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('specializations', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_users')
    # ### end Alembic commands ###
