"""message

Revision ID: aa91cf2b3d82
Revises: cc0f20c22b9d
Create Date: 2021-06-20 18:00:12.141873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa91cf2b3d82'
down_revision = 'cc0f20c22b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'category_api_id')
    op.drop_column('task', 'task_api_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_api_id', sa.INTEGER(), nullable=True))
    op.add_column('category', sa.Column('category_api_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
