"""message

Revision ID: b6560ce35c87
Revises: a1823fde1519
Create Date: 2021-06-19 23:45:13.699571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6560ce35c87'
down_revision = 'a1823fde1519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
