"""change length first and last name columns

Revision ID: b6771033a9a6
Revises: 39c007beee2e
Create Date: 2022-03-10 17:01:30.955767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6771033a9a6'
down_revision = '39c007beee2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistics', 'added_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'date_registration',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_registration',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('statistics', 'added_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
