"""message

Revision ID: cc0f20c22b9d
Revises: bf4c0ff82e45
Create Date: 2021-06-20 15:28:52.295889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0f20c22b9d'
down_revision = 'bf4c0ff82e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('write_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'write_date')
    # ### end Alembic commands ###
