"""added fields created_date, update_date in tasks

Revision ID: d12009ec27f6
Revises: 8accfa4587dd
Create Date: 2021-07-07 16:41:43.143007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12009ec27f6'
down_revision = '8accfa4587dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_date')
    op.drop_column('tasks', 'created_date')
    # ### end Alembic commands ###
