"""message

Revision ID: e327138d56b1
Revises: 7e739e2ed16b
Create Date: 2021-06-19 13:17:54.798642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e327138d56b1'
down_revision = '7e739e2ed16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('archive', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('archive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'archive')
    op.drop_column('category', 'archive')
    # ### end Alembic commands ###
