"""rename_tables_registers_useradmin

Revision ID: e5b6b151b972
Revises: 6768bc313cd1
Create Date: 2021-07-28 15:52:31.940107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5b6b151b972'
down_revision = '6768bc313cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_register_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=48), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('token_expiration_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('registers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=48), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('token_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='registers_pkey'),
    sa.UniqueConstraint('email', name='registers_email_key')
    )
    op.drop_table('admin_register_requests')
    # ### end Alembic commands ###
