"""updated ExternalSiteUser

Revision ID: eafcfd0f882d
Revises: 8e33568abb2b
Create Date: 2021-07-09 22:47:03.840551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eafcfd0f882d'
down_revision = '8e33568abb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_site_users', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('external_site_users', 'updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reasons_canceling', 'added_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'date_registration',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_registration',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reasons_canceling', 'added_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('external_site_users', 'updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('external_site_users', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
