"""add_banned_column_to_user

Revision ID: eb87749d7dc2
Revises: 3934b69146c0
Create Date: 2021-08-11 17:39:29.279229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb87749d7dc2'
down_revision = '3934b69146c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=True))
    op.execute ('UPDATE users SET banned = false') 
    op.alter_column ('users' , 'banned', nullable = False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    # ### end Alembic commands ###
