"""add columns archive and updated_date to ReasonCancelling table

Revision ID: fe33f0410510
Revises: 0ea530c95a28
Create Date: 2021-09-11 00:56:30.332894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe33f0410510'
down_revision = '0ea530c95a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reasons_canceling', sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('reasons_canceling', sa.Column('archive', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reasons_canceling', 'archive')
    op.drop_column('reasons_canceling', 'updated_date')
    # ### end Alembic commands ###
