name: Testing CI Procharity Bot

on:
  pull_request:
    branches:
      - develop
      - master
    types: [closed]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}

    steps:
      - uses: actions/checkout@v2

      - name: Update repo and restart bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          script: |
            cd /ProCharrity_bot/
            source venv/bin/activate
            git pull
