name: CI Procharity Bot

on:
  pull_request:
    branches:
      - develop
      - master
    types: [closed]

  workflow_dispatch:

jobs:
  deploy_develop:
    if: ${{ github.ref == 'develop' }}
    runs-on: ubuntu-latest

    steps:
      - name: Update repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          script: |
            cd /code
            id
            git pull origin develop

  deploy_master:
    if: ${{ github.ref == 'master' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          script: |
            cd /code
            git pull
