name: Develop Branch Procharity Bot

on:
  pull_request:
    branches:
      - develop
    types: [closed]

  workflow_dispatch:

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Github Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push Back to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/procharity_bot_back:latest
      - name: Push Front to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/procharity_bot_front:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          script: |
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker rmi $(sudo docker images -a -q)
#            sudo docker pull ${DOCKER_USERNAME}/procharity_bot_front:latest
#            sudo docker pull ${DOCKER_USERNAME}/procharity_bot_back:latest
            sudo docker-compose up --rm -d -f /code/docker-compose.yml
#            sudo docker exec -d bot_container alembic upgrade head
